# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GravityUi3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1508, 1083)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bitfinex_crypto = QtWidgets.QLabel(self.centralwidget)
        self.bitfinex_crypto.setObjectName("bitfinex_crypto")
        self.horizontalLayout_2.addWidget(self.bitfinex_crypto, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_1 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_1.setObjectName("crypto_name2_1")
        self.horizontalLayout_2.addWidget(self.crypto_name2_1, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_2 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_2.setObjectName("crypto_name2_2")
        self.horizontalLayout_2.addWidget(self.crypto_name2_2, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_3 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_3.setObjectName("crypto_name2_3")
        self.horizontalLayout_2.addWidget(self.crypto_name2_3, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_4 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_4.setObjectName("crypto_name2_4")
        self.horizontalLayout_2.addWidget(self.crypto_name2_4, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_5 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_5.setObjectName("crypto_name2_5")
        self.horizontalLayout_2.addWidget(self.crypto_name2_5, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_6 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_6.setObjectName("crypto_name2_6")
        self.horizontalLayout_2.addWidget(self.crypto_name2_6, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_7 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_7.setObjectName("crypto_name2_7")
        self.horizontalLayout_2.addWidget(self.crypto_name2_7, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_8 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_8.setObjectName("crypto_name2_8")
        self.horizontalLayout_2.addWidget(self.crypto_name2_8, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_9 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_9.setObjectName("crypto_name2_9")
        self.horizontalLayout_2.addWidget(self.crypto_name2_9, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_10 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_10.setObjectName("crypto_name2_10")
        self.horizontalLayout_2.addWidget(self.crypto_name2_10, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2_11 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2_11.setObjectName("crypto_name2_11")
        self.horizontalLayout_2.addWidget(self.crypto_name2_11, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.crypto_name = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name.setObjectName("crypto_name")
        self.horizontalLayout.addWidget(self.crypto_name, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name1 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name1.setObjectName("crypto_name1")
        self.horizontalLayout.addWidget(self.crypto_name1, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name2 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name2.setObjectName("crypto_name2")
        self.horizontalLayout.addWidget(self.crypto_name2, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3.setObjectName("crypto_name3")
        self.horizontalLayout.addWidget(self.crypto_name3, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name4 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name4.setObjectName("crypto_name4")
        self.horizontalLayout.addWidget(self.crypto_name4, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name5 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name5.setObjectName("crypto_name5")
        self.horizontalLayout.addWidget(self.crypto_name5, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name6 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name6.setObjectName("crypto_name6")
        self.horizontalLayout.addWidget(self.crypto_name6, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name7 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name7.setObjectName("crypto_name7")
        self.horizontalLayout.addWidget(self.crypto_name7, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name8 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name8.setObjectName("crypto_name8")
        self.horizontalLayout.addWidget(self.crypto_name8, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name9 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name9.setObjectName("crypto_name9")
        self.horizontalLayout.addWidget(self.crypto_name9, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name10 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name10.setObjectName("crypto_name10")
        self.horizontalLayout.addWidget(self.crypto_name10, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name11 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name11.setObjectName("crypto_name11")
        self.horizontalLayout.addWidget(self.crypto_name11, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.arbit_name1 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name1.setObjectName("arbit_name1")
        self.verticalLayout_2.addWidget(self.arbit_name1)
        self.arbit_name2 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name2.setObjectName("arbit_name2")
        self.verticalLayout_2.addWidget(self.arbit_name2)
        self.arbit_name3 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name3.setObjectName("arbit_name3")
        self.verticalLayout_2.addWidget(self.arbit_name3)
        self.arbit_name4 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name4.setObjectName("arbit_name4")
        self.verticalLayout_2.addWidget(self.arbit_name4)
        self.arbit_name5 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name5.setObjectName("arbit_name5")
        self.verticalLayout_2.addWidget(self.arbit_name5)
        self.arbit_name6 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name6.setObjectName("arbit_name6")
        self.verticalLayout_2.addWidget(self.arbit_name6)
        self.arbit_name7 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name7.setObjectName("arbit_name7")
        self.verticalLayout_2.addWidget(self.arbit_name7)
        self.arbit_name8 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name8.setObjectName("arbit_name8")
        self.verticalLayout_2.addWidget(self.arbit_name8)
        self.arbit_name9 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name9.setObjectName("arbit_name9")
        self.verticalLayout_2.addWidget(self.arbit_name9)
        self.arbit_name10 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name10.setObjectName("arbit_name10")
        self.verticalLayout_2.addWidget(self.arbit_name10)
        self.arbit_name11 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_name11.setObjectName("arbit_name11")
        self.verticalLayout_2.addWidget(self.arbit_name11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.arbit_price1 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price1.setObjectName("arbit_price1")
        self.verticalLayout.addWidget(self.arbit_price1)
        self.arbit_price2 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price2.setObjectName("arbit_price2")
        self.verticalLayout.addWidget(self.arbit_price2)
        self.arbit_price3 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price3.setObjectName("arbit_price3")
        self.verticalLayout.addWidget(self.arbit_price3)
        self.arbit_price4 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price4.setObjectName("arbit_price4")
        self.verticalLayout.addWidget(self.arbit_price4)
        self.arbit_price5 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price5.setObjectName("arbit_price5")
        self.verticalLayout.addWidget(self.arbit_price5)
        self.arbit_price6 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price6.setObjectName("arbit_price6")
        self.verticalLayout.addWidget(self.arbit_price6)
        self.arbit_price7 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price7.setObjectName("arbit_price7")
        self.verticalLayout.addWidget(self.arbit_price7)
        self.arbit_price8 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price8.setObjectName("arbit_price8")
        self.verticalLayout.addWidget(self.arbit_price8)
        self.arbit_price9 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price9.setObjectName("arbit_price9")
        self.verticalLayout.addWidget(self.arbit_price9)
        self.arbit_price10 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price10.setObjectName("arbit_price10")
        self.verticalLayout.addWidget(self.arbit_price10)
        self.arbit_price11 = QtWidgets.QLabel(self.centralwidget)
        self.arbit_price11.setObjectName("arbit_price11")
        self.verticalLayout.addWidget(self.arbit_price11)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bithumb_crypto = QtWidgets.QLabel(self.centralwidget)
        self.bithumb_crypto.setObjectName("bithumb_crypto")
        self.horizontalLayout_4.addWidget(self.bithumb_crypto, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_1 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_1.setObjectName("crypto_name3_1")
        self.horizontalLayout_4.addWidget(self.crypto_name3_1, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_2 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_2.setObjectName("crypto_name3_2")
        self.horizontalLayout_4.addWidget(self.crypto_name3_2, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_3 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_3.setObjectName("crypto_name3_3")
        self.horizontalLayout_4.addWidget(self.crypto_name3_3, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_4 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_4.setObjectName("crypto_name3_4")
        self.horizontalLayout_4.addWidget(self.crypto_name3_4, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_5 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_5.setObjectName("crypto_name3_5")
        self.horizontalLayout_4.addWidget(self.crypto_name3_5, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_6 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_6.setObjectName("crypto_name3_6")
        self.horizontalLayout_4.addWidget(self.crypto_name3_6, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_7 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_7.setObjectName("crypto_name3_7")
        self.horizontalLayout_4.addWidget(self.crypto_name3_7, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_8 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_8.setObjectName("crypto_name3_8")
        self.horizontalLayout_4.addWidget(self.crypto_name3_8, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_9 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_9.setObjectName("crypto_name3_9")
        self.horizontalLayout_4.addWidget(self.crypto_name3_9, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_10 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_10.setObjectName("crypto_name3_10")
        self.horizontalLayout_4.addWidget(self.crypto_name3_10, 0, QtCore.Qt.AlignHCenter)
        self.crypto_name3_11 = QtWidgets.QLabel(self.centralwidget)
        self.crypto_name3_11.setObjectName("crypto_name3_11")
        self.horizontalLayout_4.addWidget(self.crypto_name3_11, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1508, 23))
        self.menubar.setObjectName("menubar")
        self.menuCrypto_Show = QtWidgets.QMenu(self.menubar)
        self.menuCrypto_Show.setObjectName("menuCrypto_Show")
        self.menuTimeFrame = QtWidgets.QMenu(self.menubar)
        self.menuTimeFrame.setObjectName("menuTimeFrame")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBitcoin = QtWidgets.QAction(MainWindow)
        self.actionBitcoin.setObjectName("actionBitcoin")
        self.actionLitecoin = QtWidgets.QAction(MainWindow)
        self.actionLitecoin.setObjectName("actionLitecoin")
        self.actionEthereum = QtWidgets.QAction(MainWindow)
        self.actionEthereum.setObjectName("actionEthereum")
        self.actionBitcoin_ABC = QtWidgets.QAction(MainWindow)
        self.actionBitcoin_ABC.setObjectName("actionBitcoin_ABC")
        self.actionBitcoin_SV = QtWidgets.QAction(MainWindow)
        self.actionBitcoin_SV.setObjectName("actionBitcoin_SV")
        self.actionBitcoin_Gold = QtWidgets.QAction(MainWindow)
        self.actionBitcoin_Gold.setObjectName("actionBitcoin_Gold")
        self.actionMonero = QtWidgets.QAction(MainWindow)
        self.actionMonero.setObjectName("actionMonero")
        self.actionZech = QtWidgets.QAction(MainWindow)
        self.actionZech.setObjectName("actionZech")
        self.actionDash = QtWidgets.QAction(MainWindow)
        self.actionDash.setObjectName("actionDash")
        self.actionRipple = QtWidgets.QAction(MainWindow)
        self.actionRipple.setObjectName("actionRipple")
        self.action1_Minutes = QtWidgets.QAction(MainWindow)
        self.action1_Minutes.setObjectName("action1_Minutes")
        self.action5_Minutes = QtWidgets.QAction(MainWindow)
        self.action5_Minutes.setObjectName("action5_Minutes")
        self.action15_Minutes = QtWidgets.QAction(MainWindow)
        self.action15_Minutes.setObjectName("action15_Minutes")
        self.action30_Minutes = QtWidgets.QAction(MainWindow)
        self.action30_Minutes.setObjectName("action30_Minutes")
        self.action1_Hour = QtWidgets.QAction(MainWindow)
        self.action1_Hour.setObjectName("action1_Hour")
        self.action3_Hour = QtWidgets.QAction(MainWindow)
        self.action3_Hour.setObjectName("action3_Hour")
        self.action4_Hour = QtWidgets.QAction(MainWindow)
        self.action4_Hour.setObjectName("action4_Hour")
        self.action6_Hour = QtWidgets.QAction(MainWindow)
        self.action6_Hour.setObjectName("action6_Hour")
        self.action12_Hour = QtWidgets.QAction(MainWindow)
        self.action12_Hour.setObjectName("action12_Hour")
        self.action1_D = QtWidgets.QAction(MainWindow)
        self.action1_D.setObjectName("action1_D")
        self.action1_Week = QtWidgets.QAction(MainWindow)
        self.action1_Week.setObjectName("action1_Week")
        self.menuCrypto_Show.addAction(self.actionBitcoin)
        self.menuCrypto_Show.addAction(self.actionLitecoin)
        self.menuCrypto_Show.addAction(self.actionEthereum)
        self.menuCrypto_Show.addAction(self.actionBitcoin_ABC)
        self.menuCrypto_Show.addAction(self.actionBitcoin_SV)
        self.menuCrypto_Show.addAction(self.actionBitcoin_Gold)
        self.menuCrypto_Show.addAction(self.actionMonero)
        self.menuCrypto_Show.addAction(self.actionZech)
        self.menuCrypto_Show.addAction(self.actionDash)
        self.menuCrypto_Show.addAction(self.actionRipple)
        self.menuTimeFrame.addAction(self.action1_Minutes)
        self.menuTimeFrame.addAction(self.action5_Minutes)
        self.menuTimeFrame.addAction(self.action15_Minutes)
        self.menuTimeFrame.addAction(self.action30_Minutes)
        self.menuTimeFrame.addAction(self.action1_Hour)
        self.menuTimeFrame.addAction(self.action3_Hour)
        self.menuTimeFrame.addAction(self.action4_Hour)
        self.menuTimeFrame.addAction(self.action6_Hour)
        self.menuTimeFrame.addAction(self.action12_Hour)
        self.menuTimeFrame.addAction(self.action1_D)
        self.menuTimeFrame.addAction(self.action1_Week)
        self.menubar.addAction(self.menuCrypto_Show.menuAction())
        self.menubar.addAction(self.menuTimeFrame.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bitfinex_crypto.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_1.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_2.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_3.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_4.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_5.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_6.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_7.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_8.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_9.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_10.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2_11.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name1.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name2.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name4.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name5.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name6.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name7.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name8.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name9.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name10.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name11.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name1.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name2.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name3.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name4.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name5.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name6.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name7.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name8.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name9.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name10.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_name11.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price1.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price2.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price3.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price4.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price5.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price6.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price7.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price8.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price9.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price10.setText(_translate("MainWindow", "TextLabel"))
        self.arbit_price11.setText(_translate("MainWindow", "TextLabel"))
        self.bithumb_crypto.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_1.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_2.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_3.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_4.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_5.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_6.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_7.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_8.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_9.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_10.setText(_translate("MainWindow", "TextLabel"))
        self.crypto_name3_11.setText(_translate("MainWindow", "TextLabel"))
        self.menuCrypto_Show.setTitle(_translate("MainWindow", "Crypto Show"))
        self.menuTimeFrame.setTitle(_translate("MainWindow", "TimeFrame"))
        self.actionBitcoin.setText(_translate("MainWindow", "Bitcoin"))
        self.actionLitecoin.setText(_translate("MainWindow", "Litecoin"))
        self.actionEthereum.setText(_translate("MainWindow", "Ethereum"))
        self.actionBitcoin_ABC.setText(_translate("MainWindow", "Bitcoin ABC"))
        self.actionBitcoin_SV.setText(_translate("MainWindow", "Bitcoin SV"))
        self.actionBitcoin_Gold.setText(_translate("MainWindow", "Bitcoin Gold"))
        self.actionMonero.setText(_translate("MainWindow", "Monero"))
        self.actionZech.setText(_translate("MainWindow", "Zech"))
        self.actionDash.setText(_translate("MainWindow", "Dash"))
        self.actionRipple.setText(_translate("MainWindow", "Ripple"))
        self.action1_Minutes.setText(_translate("MainWindow", "1 Minutes"))
        self.action5_Minutes.setText(_translate("MainWindow", "5 Minutes"))
        self.action15_Minutes.setText(_translate("MainWindow", "15 Minutes"))
        self.action30_Minutes.setText(_translate("MainWindow", "30 Minutes"))
        self.action1_Hour.setText(_translate("MainWindow", "1 Hour"))
        self.action3_Hour.setText(_translate("MainWindow", "3 Hour"))
        self.action4_Hour.setText(_translate("MainWindow", "4 Hour"))
        self.action6_Hour.setText(_translate("MainWindow", "6 Hour"))
        self.action12_Hour.setText(_translate("MainWindow", "12 Hour"))
        self.action1_D.setText(_translate("MainWindow", "1 Day"))
        self.action1_Week.setText(_translate("MainWindow", "1 Week"))

